src/Entity/Relative.php
<?php

namespace App\Entity;

use App\Repository\RelativeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTime;

/**
 * @ORM\Entity(repositoryClass=RelativeRepository::class)
 */
class Relative
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @ORM\ManyToMany(targetEntity=Home::class, mappedBy="relatives")
     */
    private $homes;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="relatives")
     */
    private $createdBy;

    public function __construct()
    {
        $this->homes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthdate(): ?DateTime
    {
        return $this->birthdate;
    }

    public function setBirthdate(?DateTime $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getNextBirthday(): ?DateTime
    {
        if ($this->birthdate === null) {
            return null;
        }

        // creates a new birthday object
        $birthday = new DateTime();

        // in this new birthday : day and month of birthdate, and current year
        // so we get : when is this person's birthday this year
        $birthday->setDate(
            date('Y'),
            $this->birthdate->format('m'),
            $this->birthdate->format('d')
        );
        $birthday->setTime(0, 0, 0);
        
        // if birthday is in the past (before today) : we are past their birthday this year -> next birthday will be next year
        if($birthday < new DateTime()) {
            $birthday->modify('+1 year');
        }

        return $birthday;
    }

    public function getAge(): ?int
    {
        if ($this->birthdate === null) {
            return null;
        }

        $today = new DateTime();

        $interval = $this->birthdate->diff($today);
        return $interval->y;

    }

    public function getFullName()
    {
        return ucfirst($this->firstname) . " " . ucfirst($this->lastname);
    }

    /**
     * @return Collection|Home[]
     */
    public function getHomes(): Collection
    {
        return $this->homes;
    }

    public function addHome(Home $home): self
    {
        if (!$this->homes->contains($home)) {
            $this->homes[] = $home;
            $home->addRelative($this);
        }

        return $this;
    }

    public function removeHome(Home $home): self
    {
        if ($this->homes->contains($home)) {
            $this->homes->removeElement($home);
        }

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

}

src/Form/RelativeType.php
<?php

namespace App\Form;

use App\Entity\Home;
use App\Entity\Relative;
use App\Repository\HomeRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class RelativeType extends AbstractType
{
    private $security;

    // inject Security to be able to get "user"
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'firstname',
            TextType::class,
            [
                "label" => "Prénom",
            ]
        );

        $builder->add(
            'lastname',
            TextType::class,
            [
                "label" => "Nom",
            ]
        );

        $builder->add(
            'birthdate',
            DateType::class,
            [
                "label" => "Date de naissance",
                "required" => false,
                "widget" => "single_text"
            ]
        );

        $builder->add(
            "homes",
            EntityType::class,
            [
                "by_reference" => false, // to be able to write on the non-owner side of the relationship
                "label" => "Foyer :",
                "class" => Home::class,
                "query_builder" => function (HomeRepository $repository) {
                    // list of homes that were created by current user only
                    return $repository->queryAllByUser($this->security->getUser()->getId());
                },
                "choice_label" => "name",
                "multiple" => true,
                "expanded" => true,
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Relative::class,
        ]);
    }
}

src/Controller/RelativeController.php
<?php

namespace App\Controller;

use App\Entity\Home;
use App\Entity\Relative;
use App\Form\RelativeType;
use App\Repository\RelativeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RelativeController extends AbstractController
{
    /**
     * @Route("/relatives/{id}", name="relative_view", requirements={"id"="\d+"})
     *
     * @param Relative $relative
     *
     * @return Response
     */
    public function view(Relative $relative)
    {
        return $this->render(
            'relative/view.html.twig',
            [
                "relative" => $relative
            ]
        );
    }

    /**
     * @Route("/relatives/add", name="relative_add")
     *
     * @param Request $request
     *
     * @return RedirectResponse|Response
     */
    public function add(Request $request)
    {
        $relative = new Relative();

        $relativeForm = $this->createForm(RelativeType::class, $relative);
        $relativeForm->handleRequest($request);
        if($relativeForm->isSubmitted() && $relativeForm->isValid()) {

            // set current user as creator for this relative
            $relative->setCreatedBy($this->getUser());

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($relative);
            $manager->flush();

            //success message
            $this->addFlash("success", "Le proche a bien été ajouté");
            // TODO : error message

            // after adding relative, redirect to a page if specified
            if ($request->query->has('redirectTo')) {
                return $this->redirect($request->query->get('redirectTo'));
            }

            // else, after adding home, redirect to the "home list" page
            // TODO : re-work this logic for UX
            return $this->redirectToRoute("home_list");
        }

        return $this->render(
            'relative/add.html.twig',
            [
                "relativeForm" => $relativeForm->createView()
            ]
        );
    }

    /**
     * @Route("relatives/{id}/update", name="relative_update", requirements={"id"="\d+"})
     *
     * @param Relative $relative
     * @param Request $request
     *
     * @return RedirectResponse|Response
     */
    public function update(Relative $relative, Request $request)
    {
        $relativeForm = $this->createForm(RelativeType::class, $relative);
        $relativeForm->handleRequest($request);
        if($relativeForm->isSubmitted() && $relativeForm->isValid()) {

            $manager = $this->getDoctrine()->getManager();
            $manager->flush();

            // success message
            $this->addFlash("success", "Le proche a bien été modifié");
            // TODO : error message

            // after adding relative, redirect to a page if specified
            if ($request->query->has('redirectTo')) {
                return $this->redirect($request->query->get('redirectTo'));
            }

            // else, after adding home, redirect to the "home list" page
            // TODO : re-work this logic for UX
            return $this->redirectToRoute("home_list");
        }

        return $this->render(
            'relative/update.html.twig',
            [
                "relativeForm" => $relativeForm->createView(),
                "relative" => $relative,
            ]
        );
    }

    /**
     * @Route("relatives/{id}/delete", name="relative_delete", requirements={"id"="\d+"})
     *
     * @param Relative $relative
     *
     * @return RedirectResponse
     */
    public function delete(Relative $relative)
    {
        $manager = $this->getDoctrine()->getManager(); 
        $manager->remove($relative);
        $manager->flush();

        // success message
        $this->addFlash("success", "Supprimé de la liste");
        // TODO error message

        return $this->redirectToRoute('home_list');
    }
}

templates/relative/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h2>Ajouter un proche à la liste </h2>

	{{ form_start(relativeForm) }}
		<div class="homes-choice">
			{{ form_label(relativeForm.homes) }}
	    	{{ form_widget(relativeForm.homes) }}
			Choisir dans la liste ci-dessus, ou<a href="{{ path('home_add', { redirectTo: app.request.getPathInfo }) }}" class="new-home-link">cliquer ici pour créer un nouveau foyer</a>
		</div>
		<hr>
	    {{ form_row(relativeForm.firstname) }}
	    {{ form_row(relativeForm.lastname) }}
	    {{ form_row(relativeForm.birthdate) }}
	    <input type="submit" value="Valider" class="btn btn-primary">
		<a href="{{ path('home_list') }}" class="btn btn-secondary">Retour à la liste des foyers</a>
	{{ form_end(relativeForm) }}

{% endblock %}

templates/relative/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="d-flex flex-row justify-content-between">
    <h2>Modifier les informations de {{ relative.getFullName() }} </h2>

    <div>
        <a onClick="return confirm('Confirmez la suppression');" href="{{ path('relative_delete', {'id': relative.id}) }}" class="btn btn-danger">Supprimer</a>
    </div>
</div>

	{{ form_start(relativeForm) }}
		<div class="homes-choice">
			{{ form_label(relativeForm.homes) }}
	    	{{ form_widget(relativeForm.homes) }}
			Choisir dans la liste ci-dessus, ou<a href="{{ path('home_add', { redirectTo: app.request.getPathInfo }) }}" class="new-home-link">cliquer ici pour créer un nouveau foyer</a>
		</div>
		<hr>
	    {{ form_row(relativeForm.firstname) }}
	    {{ form_row(relativeForm.lastname) }}
	    {{ form_row(relativeForm.birthdate) }}
	    <input type="submit" value="Valider" class="btn btn-primary mt-3 mr-2">
		<a href="{{ path('home_list') }}" class="btn btn-secondary mt-3">Retour à la liste des foyers</a>
	{{ form_end(relativeForm) }}

{% endblock %}

templates/relative/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<h4 class="card-header">
					{{ relative.getFullName() }}
					<a href="{{ path('relative_update', {'id': relative.id}) }}">
						<i class="fas fa-edit float-right" style="font-size:0.7em"></i>
					</a>
				</h4>
				<div class="card-body">
					{% if relative.homes is not null %}
						{% for home in relative.homes %}
							<p>
                                <i class="fas fa-home"></i> Habite à {{ home.cityName }} ({{ home.postCode }}, {{ home.country }})
                            </p>

								{% if home.getRelatives()|length() > 1 %}
									<p class="mr-2">Avec
										{% for homeRelative in home.getRelatives() %}
											{% if homeRelative.id is not same as(relative.id) %}
												
												<a href="{{ path('relative_view', {id: homeRelative.id}) }}">
													<i class="fas fa-user"></i> {{ homeRelative.firstname|capitalize }}
												</a>
												{# TODO {% if not loop.last %}
												                        et
												                        {% endif %} #}
											{% endif %}
										{% endfor %}
									(foyer "{{ home.name|capitalize }}")
									{% endif %}
									</p>
						{% endfor %}
					{% endif %}

					{% if relative.birthdate is not null %}
						<p><i class="fas fa-birthday-cake"></i> Date de naissance :
							{{ relative.birthdate|date("d\\/m\\/Y") }}</p>
						<p>
                            <i class="far fa-clock"></i> Âge : {{ relative.age }} ans
                        </p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	{# <div class="d-flex flex-row justify-content-between">
		<h2>{{ relative.getFullName() }}</h2>
		<div>
			<a href="{{ path('relative_update', {'id': relative.id}) }}" class="btn btn-primary">Modifier</a>
		</div>
	</div>

	{% if relative.homes is not null %}
		{% for home in relative.homes %}
			<p>&#127968; Habite à
				{{ home.cityName }},
				{{ home.postCode }}</p>

			<div class="d-flex flex-row justify-content-left">
				{% if home.getRelatives()|length() > 1 %}
					<p class="mr-2">Avec
						{% for homeRelative in home.getRelatives() %}
							{% if homeRelative.id is not same as(relative.id) %}
								&#128522;
								<a href="{{ path('relative_view', {id: homeRelative.id}) }}">
									{{ homeRelative.firstname|capitalize }}
								</a>
								{# TODO {% if not loop.last %}
								                        et
								                        {% endif %} #}
							{# {% endif %}
						{% endfor %}
					</p>
					<p>(foyer "{{ home.name|capitalize }}")
					{% endif %}
				</p>
			</div>
		{% endfor %}
	{% endif %}

	{% if relative.birthdate is not null %}
		<p>&#128197; Date de naissance :
			{{ relative.birthdate|date("d\\/m\\/Y") }}</p>
		<p>&#8986; Âge :
			{{ relative.age }}
			ans</p>
	{% endif %} #}


{% endblock %}